### ISSUE TITLE
Linux Issues

### ISSUE THREAD

**Issue by zport** [OVAL-Community/OVAL#70]
Container for all Linux issues in the backlog.

**Comment by matejak** [comment]
I propose to close this issue, as issues or PRs can be tracked against their categories using labels.

**Comment by solind** [comment]
Simon is the area supervisor for Unix; he should have the authority to close this.

**Comment by matejak** [comment]
> Simon is the area supervisor for Unix; he should have the authority to close this.

Šimon is no longer a Red Hat employee, and after discussing this with @adammontville I took over those positions for the time being.

**Comment by solind** [comment]
Indeed, I thought he'd left but I wasn't sure -- and he is still listed as the area supervisor in the community process documentation.

Since supervisors are (according to the process) merely appointed by the "sponsor" (CIS), @adammontville should be able to grant you official status.  In which case, you would have the authority to close this issue yourself!
