### ISSUE TITLE
Proposed OVAL Updates For Microsoft Internet Information Server (IIS) Settings Using AppCmd.exe - appcmd Test

### ISSUE THREAD

**Issue by bryanlwilson** [OVAL-Community/OVAL#76]
**Abstract**
OVAL 5.11.2 lacks a robust, straight-forward, and efficient mechanism to query Microsoft Internet
Information Server (versions 7.0 – 10) configuration settings. The existing OVAL cmdlet test is
inadequate as it fails to provide adequate data resolution. For instance, if an Internet Information
Server (IIS) installation hosts multiple websites, the cmdlet test results do not enable the user to
determine from which website a reported setting was collected.
The Microsoft AppCmd.exe application is the primary method for querying and managing IIS
servers. We propose two new OVAL tests, the appcmd and appcmdlistconfig tests to query IIS
data using AppCmd.exe.
This ticket defines the proposed appcmd test. See a related ticket (proposal) covering the appcmdlistconfig test.

**Link to Proposal**
The proposal is attached to this ticket as a PDF file.  It is dated May 03, 2019, and is updated to version 1.1.  Please review document for OVAL Update.

**Additional context**
[win-def_appcmd_addition_v1.1.pdf](https://github.com/OVAL-Community/OVAL/files/3142344/win-def_appcmd_addition_v1.1.pdf)

[win-def_appcmd_addition_v1.1.zip](https://github.com/OVAL-Community/OVAL/files/3142290/win-def_appcmd_addition_v1.1.zip)

**Comment by wmunyan** [comment]
Can you please add the declarations of the EntityObjectAppCmdObjectType and EntityItemAppCmdObjectType elements? Are these enumerations?

**Comment by wmunyan** [comment]
Quick comment:
The `identifier` element in the `appcmd_object` has some documentation around when `xsi:nil=true`, but the element isn't identified as `nillable=true`

CIS did a more elaborate extension schema for IIS a while back, so we'll have to check how we can map that to the new schema.  More to follow on that one.

Cheers, 
-Bill M.

**Comment by bryanlwilson** [comment]
Please review updated content update files.  I have updated per your comments.

[appcmd_updates_windows-schema.zip](https://github.com/OVAL-Community/OVAL/files/3158878/appcmd_updates_windows-schema.zip)

**Comment by wmunyan** [comment]
I'll preface by saying that I _think_ I'm looking at the latest version of the schema.  It looks like the `nillable` attribute is still missing from any elements that may require it.  Also, the element descriptions still reference a "relative dn", which seems like its a cut/paste from some other elements.

**Comment by zport** [comment]
Hi @bryanlwilson and @wmunyan -

Any further thoughts on this or issue #77? Is the `nillable` attribute still missing from the schemas? What should the element descriptions reference instead of the "relative dn"?

Thanks!

**Comment by solind** [comment]
Hey everyone, I commented on the issue.  Maybe I should comment here instead?

I think we could make this an XML-oriented test, since appcmd.exe has a ```/xml``` option.  We'd keep the identifier_type (although to me this should be renamed object_type, because that's what the command-line help calls these enumerated options).

We'd eliminate identifier and section from the object, and identifier, section and result from the state and item.

We'd accordingly add an xpath to the object, state and item, and also a value_of to the state and item (with maxOccurs="unlimited").

**Comment by bryanlwilson** [comment]
Just wanted to note that I am working (have been working) this issue with David offline.  More to come, I will update this group with my response.

**Comment by bryanlwilson** [comment]
Here are the content files delivered to disa they contain implemented appcmd and appcmdlistconfig tests.

[U_IIS_8-5_Server_STIG_V1R1.001.zip](https://github.com/OVAL-Community/OVAL/files/3402998/U_IIS_8-5_Server_STIG_V1R1.001.zip)
[U_IIS_8-5_Site_STIG_V1R1.001.zip](https://github.com/OVAL-Community/OVAL/files/3403000/U_IIS_8-5_Site_STIG_V1R1.001.zip)

**Comment by wmunyan** [comment]
Has there been any movement on these proposals?  An above comment references some offline conversations that could result in changes to the proposed schema.

Have any updates been made?  Can a PR be added to incorporate the new tests into the Windows schema?

**Comment by solind** [comment]
Only that after some back-and-forth and a considerable amount of time without making progress, I have become convinced that a command-line-based test (more or less as originally proposed) would be fine.

I'd like to see a PR so that we can prototype an implementation.

**Comment by bryanlwilson** [comment]
[IIS_appcmd_test_Jan2021.zip](https://github.com/OVAL-Community/OVAL/files/5816808/IIS_appcmd_test_Jan2021.zip)

I have finalized the appcmd test based on comments received here.  The zip file is attached including example content and schema updates.  Note the following updates were made to this version.

1) The item element called "object" has had it's name changed to "identifier_type". This element defines the identifier type (Apppool, Site, or VDir).
2) There were issues with some of the descriptions noting that xsi:nil="true" when the item element didn't require this. Those "xsd:documentation" field entries have been updated.

**Comment by vanderpol** [comment]
Thanks Bryan, I'll be updating my branch with your updates and submitting a PR on this tomorrow.

**Comment by solind** [comment]
Hi @bryanlwilson and @vanderpol -- here are OVAL results files made from your sample Definitions files (attached).

There is an issue in the DISA sample: because appcmd_item/result is an EntityItemStringType and appcmd_state/result is an EntityStateStringType, you cannot perform a "GREATER_THAN" comparison.  If you want to have this capability, we should use Entity[State/Item]AnySimpleType, and then a datatype can be specified in the state.

Do you have any samples for the appcmdlistconfig_test?

[IIS_appcmd_test_results_Mar2021.zip](https://github.com/OVAL-Community/OVAL/files/6118795/IIS_appcmd_test_results_Mar2021.zip)

**Comment by wmunyan** [comment]
im just starting to look at getting this implemented as well, and have gone through mapping the 2 new tests to our IIS benchmarks in order to ensure we have the ability to make the switch over to these new tests instead of the "internal extensions" we've done previously.  It looks to be that we can accomplish what we need to using the new tests, so that's good!  I will work on the implementation as soon as I can get to it, but I agree with @solind that the `Entity(State|Item)AnySimpleType` is a good idea in order to allow for all the comparison operations

**Comment by bryanlwilson** [comment]
@solind I have a attached some example content for appcmdlistconfig.  I will give you a response to your question early next week.  I need to research.[
[win-def_appcmdlistconfig_test_examples.txt](https://github.com/OVAL-Community/OVAL/files/6132665/win-def_appcmdlistconfig_test_examples.txt)
]

**Comment by solind** [comment]
Thanks @bryanlwilson , this is very helpful!

**Comment by solind** [comment]
Hi @bryanlwilson , I've attached my sample OVAL results for those two example inputs.

Everything looks good to me, except for the non-existing param case (exhibited by oval:mil.ssclant.oval.test:tst:9). I think the right thing to do is to say the object "does not exist" (as in my results) instead of generating an error (which is what the comment suggested).

[appcmdlistconfig_results.zip](https://github.com/OVAL-Community/OVAL/files/6133349/appcmdlistconfig_results.zip)

**Comment by bryanlwilson** [comment]
@solind @vanderpol 

Thanks so much for the feedback.. Here are my responses.

1. I concur that for the appcmd test the result (which is currently an EntityStateStringType) should use Entity[State/Item]AnySimpleType. This allows for GREATER_THAN, etc comparisions. Great catch.
2. This is a bug in SCC.  I concur that tst:9 should result in error.  In this case the Object has a parameter that is not valid, it appears SCC isn't handling this error properly.  In tst:8 SCC correctly reports error status for a "bad" section.  There must be something wrong with our error handling of a bad parameter.  I need to see if I can replicate in our lab  

<oval-sc:object id="oval:mil.ssclant.oval.test:obj:9" version="1" comment="Error Example - AppCmd.exe reports error due to incorrect parameter setting" flag="does not exist"></oval-sc:object>

The tool should translate the error reported from appcmd and correctly sets error status (like tst:8).  I will log this bug and it will be fixed in our next minor release.  

My questions:
1. For appcmdlistconfig don't we need to do the same result update as in item 1?  Changing Result from EntityStateStringType) to Entity[State/Item]AnySimpleType for both appcmd and appcmdlistconfig seems to make sense.  Great catch.

2. Do you need me to update my schema files for the changes noted above or can you do it on your end?  I don't have a problem with updating and resubmitting but it seems like a pretty easy update you could make to schema files I'll submitted.  But let me know if you are fixing it or you need me to.  This update to appcmd and appcmdlistconfig will mean an update for SCC is needed in our schema files used by the tool.  Which means we will have to release a minor version update once appcmd and appcmdlistconfig are finalized.

**Comment by solind** [comment]
Hi Bryan, yes indeed, both result elements should be changed to Entity[State/Item]AnySimpleType.

Ideally @vanderpol would make the change, because it's his PR (pull request).  He should be able to edit the files, commit the changes in Git, and just push the change to his repo.  That will update the PR automatically.

Someone else could do it, but then we'd have to close your PR and open a new one.

**Comment by wmunyan** [comment]
I feel like there might be a difference in how item statuses are handled based on what information isn't correct.  For example, if the `identifier_type` is "Site" and the `identifier` is "Non-Existent Site Name", then to me, the corresponding `appcmd_item` and `appcmdlistconfig_item` would have a status of "does not exist".

However, if the `identifier_type` and `identifier` do exist, i.e. an existing site name, but either the `section` or `parameter` are incorrectly specified, then a status of "error" would go on the corresponding item.

**Comment by solind** [comment]
How can you tell there's an "incorrectly"-specified section or parameter, as opposed to simply a poorly- (or incompletely-) configured identifier_type/identifier combination?  To me this is like specifying a registry key (which may exist) and a value that does not exist.  In this case we don't create an item in an error state, we say the object does not exist.  There is no way to know, based on a single registry object, whether it doesn't exist because of the absence of the key, or the value.

On the other hand, there are two different possible return codes from appcmd.exe.  I don't recall if the command consistently returns one or the other for a non-existing identifier vs a non-existing param vs. a non-existing section:

```
int ERROR_INVALID_FUNCTION = 1;
int ERROR_INVALID_INDEX = 1413;
```

One could always create "partial match" items, but, their presence or absence couldn't have any impact on the test evaluation, so that wouldn't be useful if it's necessary to differentiate between them in the context of a test.

On the other hand, there is currently no way to assert the existence of an identifier-type/identifier combination.  Perhaps we should make the param entity in appcmd_object xsi:nil-able, so that this can be tested without necessarily having to know a valid param.

**Comment by bryanlwilson** [comment]
@solind @wmunyan

I understand your issue now.  I concur with your comments.  If appcmd doesn't "work" because of a bad parameter or section the result should be doesn't exist.  I will update SCC to report a warning to help content author if appcmd reports an error when a test is attempted but as you noted SCC needs to handle this as Does Not Exist and not report an error or error status.

**Comment by wmunyan** [comment]
PR has been merged; resolving this issue
